### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by mjarcem** [swarm-lab/ROpenCV#2]
Hello everybody, 

I have installed many times OpenCv on particular computer but I have problems installing it on my work computer. I need to install it in order to install R-vision package. 

I'm working with R 3.6.3, Rtools35 and Cmake 2.15 (I've tried different Cmake versions but I got the same error). I partitioned my temporary files to a path without any blank spaces and accents, and installed R, Rtools and Cmake in the same location also without any accents and blank spaces.

The error I got is this one and I cannot figure out what the problem is: 

`MINGW3~1.EXE[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/common/gcompoundkernel.cpp.obj
[100%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/api/s11n.cpp.obj
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gproto.hpp:21,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcomputation.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi.hpp:30,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/render/render.hpp:13,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/api/render_priv.hpp:11,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/api/render_ocv.hpp:2,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/render/grenderocv.cpp:3:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcall.hpp:11,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gkernel.hpp:20,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/core.hpp:19,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/precomp.hpp:14,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/plaidml/gplaidmlcore.cpp:8:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcall.hpp:11,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gkernel.hpp:20,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/core.hpp:19,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/precomp.hpp:14,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/common/gcompoundbackend.cpp:8:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gproto.hpp:21,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcomputation.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/s11n.hpp:14,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/api/s11n.cpp:7:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcall.hpp:11,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gkernel.hpp:20,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/core.hpp:19,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/precomp.hpp:14,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/common/gcompoundkernel.cpp:8:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
CMakeFiles/Makefile2:1942: recipe for target 'modules/gapi/CMakeFiles/opencv_gapi.dir/all' failed
MINGW3~1.EXE[1]: *** [modules/gapi/CMakeFiles/opencv_gapi.dir/all] Error 2
MINGW3~1.EXE[1]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
makefile:162: recipe for target 'all' failed
MINGW3~1.EXE: *** [all] Error 2
MINGW3~1.EXE: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[1]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[  2%] Built target zlib
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[  9%] Built target libjpeg-turbo
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 14%] Built target libtiff
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 28%] Built target libwebp
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 30%] Built target libopenjp2
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 32%] Built target libpng
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 44%] Built target IlmImf
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 45%] Built target quirc
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 47%] Built target ade
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 47%] Built target opencv_videoio_plugins
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 58%] Built target opencv_core
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 58%] Built target opencv_flann
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 67%] Built target opencv_imgproc
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 69%] Built target opencv_ml
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 71%] Built target opencv_photo
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 75%] Built target opencv_features2d
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 78%] Built target opencv_imgcodecs
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 80%] Built target opencv_videoio
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 85%] Built target opencv_calib3d
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 86%] Built target opencv_highgui
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 87%] Built target opencv_objdetect
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 89%] Built target opencv_stitching
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 90%] Built target opencv_video
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
MINGW3~1.EXE[2]: Entering directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
[ 90%] Building CXX object modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ie/giebackend.cpp.obj
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/mat.hpp:14:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/garg.hpp:15,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gcall.hpp:11,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/gkernel.hpp:20,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/core.hpp:19,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/precomp.hpp:14,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/ie/giebackend.cpp:7:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:71:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable: 4244)
 ^
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/own/saturate.hpp:75:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(default: 4244)
 ^
In file included from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/ie/giebackend.hpp:11:0,
                 from C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/src/backends/ie/giebackend.cpp:11:
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/infer/ie.hpp: In constructor 'cv::gapi::ie::Params<cv::gapi::Generic>::Params(const string&, const string&, const string&, const string&)':
C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/modules/gapi/include/opencv2/gapi/infer/ie.hpp:129:77: error: converting to 'std::unordered_map<std::basic_string<char>, std::pair<cv::Mat, cv::gapi::ie::TraitAs> >' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<cv::Mat, cv::gapi::ie::TraitAs>; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<cv::Mat, cv::gapi::ie::TraitAs> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<cv::Mat, cv::gapi::ie::TraitAs> > >]'
         : desc{ model, weights, device, {}, {}, {}, 0u, 0u, true}, m_tag(tag) {
                                                                             ^
modules/gapi/CMakeFiles/opencv_gapi.dir/build.make:861: recipe for target 'modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ie/giebackend.cpp.obj' failed
MINGW3~1.EXE[2]: *** [modules/gapi/CMakeFiles/opencv_gapi.dir/src/backends/ie/giebackend.cpp.obj] Error 1
MINGW3~1.EXE[2]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
CMakeFiles/Makefile2:1942: recipe for target 'modules/gapi/CMakeFiles/opencv_gapi.dir/all' failed
MINGW3~1.EXE[1]: *** [modules/gapi/CMakeFiles/opencv_gapi.dir/all] Error 2
MINGW3~1.EXE[1]: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
makefile:162: recipe for target 'all' failed
MINGW3~1.EXE: *** [all] Error 2
MINGW3~1.EXE: Leaving directory 'C:/Users/GMFQA/AppData/Local/Temp/RtmpqcIRIo/opencv-4.5.0/build32'
> isOpenCVInstalled()
[1] FALSE `

I don't really understand where are pragmas warnings coming from ? 

Thankyou for your answers 

Maria

**Comment by sjmgarnier** [comment]
@mjarcem This repository is currently inactive. Please use the [ROpenCVLite repository](https://github.com/swarm-lab/ROpenCVLite) instead to post your questions. Thanks.
